let scale = 10;
let x = 0;
let y = 0;
let i = 1;
let speedx = 10;
let speedy = 10;
let appletail = 0;
let score = 0;
let level = 1;
let current_best_score = 0;
let time = 1000;
let preffered = 0;
let eats = false;
let game_over = false;
let appleEaten = false;
let interval;
let pause = false;
let direction = "";
let fruitx = Math.floor(Math.random() * 50) * 10;
let fruity = Math.floor(Math.random() * 50) * 10;
let snake = [{}, { p1: 0, p2: 0 }];
let playground;
let context;
let formaldir = "";
let opdir = "";
let str = "";
let local_dir = "";
let apple = Math.floor(Math.random()) + 1;
let appleX = Math.floor(Math.random() * 50) * 10;
let appleY = Math.floor(Math.random() * 50) * 10;
let head = new Image();
let img = new Image();